import { Theme } from '../types';

export const THEMES: Record<string, Theme> = {
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian Flow',
    type: 'dark',
    preview: '#1a1a1a',
    bg: 'bg-black',
    text: 'text-gray-200',
    textSecondary: 'text-gray-500',
    accent: 'bg-white/10 text-white',
    accentHover: 'hover:bg-white/20',
    panel: 'bg-black/60 backdrop-blur-xl border-r border-white/5',
    border: 'border-white/5',
    bubbleUser: 'bg-white/5 backdrop-blur-sm border border-white/5 text-gray-100',
    bubbleAi: 'bg-transparent text-gray-300',
    input: 'bg-white/5 backdrop-blur-xl',
  },
  nebula: {
    id: 'nebula',
    name: 'Nebula Glass',
    type: 'dark',
    preview: 'linear-gradient(135deg, #0f0c29, #302b63)',
    bg: 'bg-[#0f0c29]',
    text: 'text-white',
    textSecondary: 'text-purple-200/60',
    accent: 'bg-purple-500/30 text-purple-100',
    accentHover: 'hover:bg-purple-500/50',
    panel: 'bg-white/5 backdrop-blur-2xl border-r border-white/10',
    border: 'border-white/10',
    bubbleUser: 'bg-white/10 backdrop-blur-md border border-white/20 text-white',
    bubbleAi: 'bg-black/20 backdrop-blur-md border border-white/5 text-purple-50',
    input: 'bg-white/10 backdrop-blur-2xl border border-white/20',
  },
  kinetic: {
    id: 'kinetic',
    name: 'Kinetic Typographic',
    type: 'dark',
    preview: '#0a0a0a',
    bg: 'bg-neutral-950',
    text: 'text-white font-display tracking-tighter',
    textSecondary: 'text-neutral-500',
    accent: 'bg-white text-black font-bold uppercase',
    accentHover: 'hover:bg-neutral-200',
    panel: 'bg-neutral-900 border-r border-neutral-800',
    border: 'border-neutral-800',
    bubbleUser: 'bg-transparent text-white text-right font-bold text-xl md:text-2xl',
    bubbleAi: 'bg-transparent text-neutral-300 text-3xl md:text-5xl font-bold leading-tight',
    input: 'bg-neutral-900',
  },
  bioluminescent: {
    id: 'bioluminescent',
    name: 'Bioluminescent Deep',
    type: 'dark',
    preview: 'linear-gradient(135deg, #020617, #0891b2)',
    bg: 'bg-[#020617]',
    text: 'text-cyan-100',
    textSecondary: 'text-cyan-900',
    accent: 'bg-cyan-500/20 text-cyan-400 shadow-[0_0_15px_rgba(34,211,238,0.4)]',
    accentHover: 'hover:bg-cyan-500/30',
    panel: 'bg-slate-950/80 border-r border-cyan-900/30',
    border: 'border-cyan-500/20',
    bubbleUser: 'bg-cyan-950/40 border border-cyan-500/30 text-cyan-50 shadow-[0_0_10px_rgba(6,182,212,0.1)]',
    bubbleAi: 'bg-transparent text-cyan-200/90 shadow-[0_0_2px_rgba(6,182,212,0.2)]',
    input: 'bg-slate-900/90 border border-cyan-500/30',
  },
  porcelain: {
    id: 'porcelain',
    name: 'Porcelain & Gold',
    type: 'light',
    preview: 'linear-gradient(135deg, #FDFBF7, #D4AF37)',
    bg: 'bg-[#FDFBF7]',
    text: 'text-stone-800',
    textSecondary: 'text-stone-400',
    accent: 'bg-[#D4AF37] text-white shadow-md',
    accentHover: 'hover:bg-[#C5A028]',
    panel: 'bg-[#FDFBF7] border-r border-stone-100',
    border: 'border-[#D4AF37]/20',
    bubbleUser: 'bg-[#FDFBF7] shadow-[inset_2px_2px_5px_rgba(0,0,0,0.05),inset_-2px_-2px_5px_rgba(255,255,255,1)] text-stone-800 rounded-xl',
    bubbleAi: 'bg-transparent text-stone-600',
    input: 'bg-[#FDFBF7] shadow-[5px_5px_10px_#e6e6e6,-5px_-5px_10px_#ffffff]',
  },
  prism: {
    id: 'prism',
    name: 'Prism Refraction',
    type: 'light',
    preview: 'linear-gradient(135deg, #fff, #f0f0f0)',
    bg: 'bg-white',
    text: 'text-gray-900',
    textSecondary: 'text-gray-400',
    accent: 'bg-black text-white',
    accentHover: 'hover:bg-gray-800',
    panel: 'bg-white/80 backdrop-blur-xl border-r border-white/20 shadow-xl',
    border: 'border-gray-100',
    bubbleUser: 'bg-white/40 border border-white/60 shadow-lg text-gray-900 backdrop-blur-md', // Needs rainbow border in CSS
    bubbleAi: 'bg-transparent text-gray-800',
    input: 'bg-white/60 backdrop-blur-xl border border-white/50 shadow-lg',
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber-Noir Terminal',
    type: 'dark',
    preview: 'linear-gradient(135deg, #050505, #ff2a6d)',
    bg: 'bg-[#050505]',
    text: 'text-[#ff2a6d]',
    textSecondary: 'text-[#ff2a6d]/40',
    accent: 'bg-[#ff2a6d] text-black font-mono font-bold',
    accentHover: 'hover:bg-[#ff2a6d]/80',
    panel: 'bg-[#050505] border-r border-[#ff2a6d]/20',
    border: 'border-[#ff2a6d]/30',
    bubbleUser: 'bg-[#ff2a6d]/10 border border-[#ff2a6d] text-[#ff2a6d]',
    bubbleAi: 'bg-transparent text-[#05d9e8]',
    input: 'bg-[#0a0a0a] border border-[#ff2a6d]/50',
  },
  zen: {
    id: 'zen',
    name: 'Zen Garden',
    type: 'light',
    preview: 'linear-gradient(135deg, #E6E0D4, #8C9A87)',
    bg: 'bg-[#E6E0D4]',
    text: 'text-[#5C5546]',
    textSecondary: 'text-[#8A8374]',
    accent: 'bg-[#8C9A87] text-white',
    accentHover: 'hover:bg-[#7A8875]',
    panel: 'bg-[#E6E0D4] border-r border-[#D6CFC3]',
    border: 'border-[#D6CFC3]',
    bubbleUser: 'bg-[#D6CFC3] text-[#5C5546] rounded-2xl shadow-sm',
    bubbleAi: 'bg-transparent text-[#5C5546]',
    input: 'bg-[#D6CFC3]/50',
  },
  invisible: {
    id: 'invisible',
    name: 'Invisible UI',
    type: 'dark',
    preview: '#000',
    bg: 'bg-black',
    text: 'text-white',
    textSecondary: 'text-white/40',
    accent: 'bg-white/20 text-white backdrop-blur-md',
    accentHover: 'hover:bg-white/30',
    panel: 'bg-black/20 backdrop-blur-sm border-r border-white/5',
    border: 'border-white/5',
    bubbleUser: 'bg-transparent border-none text-white font-medium text-lg drop-shadow-md',
    bubbleAi: 'bg-transparent border-none text-white/90 drop-shadow-md',
    input: 'bg-white/10 backdrop-blur-md border-none',
  },
  morphic: {
    id: 'morphic',
    name: 'Morphic Metal',
    type: 'dark',
    preview: 'linear-gradient(135deg, #1a1a1a, #444)',
    bg: 'bg-[#1a1a1a]',
    text: 'text-white',
    textSecondary: 'text-gray-400',
    accent: 'bg-gradient-to-r from-gray-200 to-white text-black shadow-lg',
    accentHover: 'hover:scale-105',
    panel: 'bg-[#1a1a1a]/80 backdrop-blur-md border-r border-white/10',
    border: 'border-white/10',
    bubbleUser: 'bg-gradient-to-br from-[#2a2a2a] to-[#000] border border-white/5 text-gray-200 shadow-inner',
    bubbleAi: 'bg-transparent text-gray-300',
    input: 'bg-[#2a2a2a] shadow-inner',
  },
  arcade: {
    id: 'arcade',
    name: 'Arcade Fun',
    type: 'dark',
    preview: 'linear-gradient(135deg, #312e81, #22c55e)',
    bg: 'bg-indigo-950',
    text: 'text-green-400',
    textSecondary: 'text-green-600',
    accent: 'bg-green-500 text-black font-arcade shadow-[4px_4px_0px_#000]',
    accentHover: 'hover:translate-y-1 hover:shadow-none',
    panel: 'bg-gray-900 border-r-4 border-black',
    border: 'border-green-500/50',
    bubbleUser: 'bg-blue-600 text-white font-arcade border-2 border-black shadow-[4px_4px_0px_rgba(0,0,0,0.5)]',
    bubbleAi: 'bg-black text-green-400 font-arcade border-2 border-green-500 shadow-[0_0_10px_rgba(34,197,94,0.4)]',
    input: 'bg-black border-2 border-green-500',
  }
};